[package]
name = "compare_icon_fonts"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
regex = "1.12.2"
skrifa = "0.35.0"
# sleipnir = "0.2.13"
sleipnir = { path = "../sleipnir" }
